[project]
name = "flowwer"
version = "0.2.1"
description = "Flowwer - A VaultWares Project"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.95.0",
    "uvicorn>=0.21.0",
    "python-dotenv>=1.0.0",
    "pydantic>=1.10.0"
]

[dependency-groups]
dev = [
    "mypy>=1.15",
    "pytest>=8.0"
]

[tool.uv]
exclude-newer = "7 days"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.sources]
"worker.py" = "worker.py"
